import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider, CssBaseline } from "@mui/material";
import PostDialogLayout from "./components/PostDialogLayout";
import theme from "./theme";
import "./globals.css";
import Footer from "./components/Footer";
import { NotificationsDrawerProvider } from "./Context/NotificationsDrawerContext";
import { CreateProfileProvider } from "./Context/CreateProfileContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Path Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CreateProfileProvider>
              <PostDialogLayout>
                <NotificationsDrawerProvider>
                  <CssBaseline />
                  <main
                    style={{
                      flex: 1,
                      display: "flex",
                      flexDirection: "column",
                    }}
                  >
                    {children}
                  </main>
                  <Footer />
                </NotificationsDrawerProvider>
              </PostDialogLayout>
            </CreateProfileProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
