import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider, CssBaseline } from "@mui/material";
import PostDialogLayout from "./components/PostDialogLayout";
import theme from "./theme";
import "./globals.css";
import Footer from "./components/Footer";
import { NotificationsDrawerProvider } from "./Context/NotificationsDrawerContext";
import { CreateProfileProvider } from "./Context/CreateProfileContext";
import { FollowersDialogProvider } from "./Context/FollowersDialogContext";
import { AuthGuardProvider } from "./Context/AuthGuardContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Path Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AppRouterCacheProvider>
          <AuthGuardProvider>
            <ThemeProvider theme={theme}>
              <CreateProfileProvider>
                <PostDialogLayout>
                  <NotificationsDrawerProvider>
                    <FollowersDialogProvider>
                      <CssBaseline />
                      <main
                        style={{
                          flex: 1,
                          display: "flex",
                          flexDirection: "column",
                        }}
                      >
                        {children}
                      </main>
                      <Footer />
                    </FollowersDialogProvider>
                  </NotificationsDrawerProvider>
                </PostDialogLayout>
              </CreateProfileProvider>
            </ThemeProvider>
          </AuthGuardProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
